<?php

use Illuminate\Database\Seeder;
use App\Models\ProductVariant;

class ProductVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lines = [
            ['product_id' => '1', 'sku' => 'STOD124', 'product_code' => '124', 'technical_description' => 'Rica em Farinhas Funcionais. Comparado a mussarela de leite de vaca a mussarela de Búfala contem menos gordura e sódio, além de ser ótima fonte de proteína, Cálcio, Vitaminas A, B2 e D.', 'marketing_description' => 'A Buffalina, por ser feita com mussarela de Búfala, contem menos gordura e sódio. É uma ótima fonte de proteína, cálcio e vitaminas A,B2 e D.', 'subcategory_id' => '7', 'status' => 'A'],
            ['product_id' => '1', 'sku' => 'STOD2410', 'product_code' => '2410', 'technical_description' => 'Rica em Farinhas Funcionais. Comparado a mussarela de leite de vaca a mussarela de Búfala contem menos gordura e sódio, além de ser ótima fonte de proteína, Cálcio, Vitaminas A, B2 e D.', 'marketing_description' => 'A Buffalina, por ser feita com mussarela de Búfala, contem menos gordura e sódio. É uma ótima fonte de proteína, cálcio e vitaminas A,B2 e D.', 'subcategory_id' => '7', 'status' => 'A'],
            ['product_id' => '2', 'sku' => 'STOD1651', 'product_code' => '1651', 'technical_description' => 'Caldo sem glúten a base de batata e couve manteiga com legumes e bacon.', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'subcategory_id' => '3', 'status' => 'A'],
            ['product_id' => '3', 'sku' => 'STOD1678', 'product_code' => '1678', 'technical_description' => 'Caldo sem glúten de frango com arroz, batata, cenoura e legumes.', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'subcategory_id' => '3', 'status' => 'A'],
            ['product_id' => '4', 'sku' => 'STOD2925', 'product_code' => '2925', 'technical_description' => 'Deliciosa, leve e com recheio. Sem Glúten.', 'marketing_description' => 'A nossa coxinha alem de ser saborosa e leve, não contem gluten!', 'subcategory_id' => '1', 'status' => 'A'],
            ['product_id' => '4', 'sku' => 'STOD1927', 'product_code' => '1927', 'technical_description' => 'Deliciosa, leve e com recheio. Sem Glúten.', 'marketing_description' => 'A nossa coxinha alem de ser saborosa e leve, não contem gluten!', 'subcategory_id' => '1', 'status' => 'A'],
            ['product_id' => '5', 'sku' => 'STOD2933', 'product_code' => '2933', 'technical_description' => 'O Alho Poró é uma fibra prebiótica que auxilia na defesa da mucosa intestinal.', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'subcategory_id' => '8', 'status' => 'A'],
            ['product_id' => '5', 'sku' => 'STOD2623', 'product_code' => '2623', 'technical_description' => 'O Alho Poró é uma fibra prebiótica que auxilia na defesa da mucosa intestinal.', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'subcategory_id' => '8', 'status' => 'A'],
            ['product_id' => '6', 'sku' => 'STOD2771', 'product_code' => '2771', 'technical_description' => 'A Carne de Jaca é rica em vitaminas e minerais, como o ferro, o potássio, o cálcio e o fósforo. Tem o poder de prevenir a anemia, regular a pressão arterial e combater radicais livres.', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'subcategory_id' => '8', 'status' => 'A'],
            ['product_id' => '7', 'sku' => 'STOD2763', 'product_code' => '2763', 'technical_description' => 'O Palmito tem baixo teor de gorduras, fornece nutrientes como vitaminas A, C, do complexo B e importantes minerais como o sódio e o potássio.', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'subcategory_id' => '8', 'status' => 'A'],
            ['product_id' => '8', 'sku' => 'STOD140', 'product_code' => '140', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose.', 'marketing_description' => 'A nossa para Lasanha é rica em farinhas funcionais e não contem glúten!', 'subcategory_id' => '6', 'status' => 'A'],
            ['product_id' => '9', 'sku' => 'STOD167', 'product_code' => '167', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'marketing_description' => 'A nossa Massa para pastel é leve  e não contem lactose!', 'subcategory_id' => '5', 'status' => 'A'],
            ['product_id' => '10', 'sku' => 'STOD159', 'product_code' => '159', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Contem como diferencial a Semente de Girassol,  com importante papel para a promoção da saúde do sistema imunológico e produção de anticorpos e o AMARANTO, fonte de proteínas, rico em minerais, como o cálcio, o magnésio e o fósforo, o amaranto fortalece os ossos e os dentes, além de ser rico em Ferro.', 'marketing_description' => 'A nossa Massa para pizza possui semente de Girassol, que ajuda na saúde do sistema imunológico e na produção de anticorpos, alem de ser levissíma!', 'subcategory_id' => '5', 'status' => 'A'],
            ['product_id' => '11', 'sku' => 'STOD2747', 'product_code' => '2747', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'subcategory_id' => '10', 'status' => 'A'],
            ['product_id' => '12', 'sku' => 'STOD2379', 'product_code' => '2379', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'subcategory_id' => '9', 'status' => 'A'],
            ['product_id' => '13', 'sku' => 'STOD3009', 'product_code' => '3009', 'technical_description' => 'Molho ao sugo Vegano e sem glúten.', 'marketing_description' => '', 'subcategory_id' => '13', 'status' => 'A'],
            ['product_id' => '14', 'sku' => 'STOD2739', 'product_code' => '2739', 'technical_description' => 'A batata doce é um carboidrato de absorção lenta, portanto, não aumenta de forma brusca os níveis de glicose no sangue, fonte de vitaminas A e C.', 'marketing_description' => 'A batata doce já é muito conhecida por aqueles que buscam uma opção de carboidrato ', 'subcategory_id' => '10', 'status' => 'A'],
            ['product_id' => '14', 'sku' => 'STOD2712', 'product_code' => '2712', 'technical_description' => 'A batata doce é um carboidrato de absorção lenta, portanto, não aumenta de forma brusca os níveis de glicose no sangue, fonte de vitaminas A e C.', 'marketing_description' => 'A batata doce já é muito conhecida por aqueles que buscam uma opção de carboidrato ', 'subcategory_id' => '10', 'status' => 'A'],
            ['product_id' => '15', 'sku' => 'STOD2968', 'product_code' => '2968', 'technical_description' => 'Rica em Farinhas Funcionais.', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'subcategory_id' => '4', 'status' => 'A'],
            ['product_id' => '15', 'sku' => 'STOD2631', 'product_code' => '2631', 'technical_description' => 'Rica em Farinhas Funcionais.', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'subcategory_id' => '4', 'status' => 'A'],
            ['product_id' => '16', 'sku' => 'STOD2976', 'product_code' => '2976', 'technical_description' => 'Rica em Farinhas Funcionais.', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'subcategory_id' => '4', 'status' => 'A'],
            ['product_id' => '16', 'sku' => 'STOD2798', 'product_code' => '2798', 'technical_description' => 'Rica em Farinhas Funcionais.', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'subcategory_id' => '4', 'status' => 'A'],
            ['product_id' => '17', 'sku' => 'STOD2801', 'product_code' => '2801', 'technical_description' => 'Rica em Farinhas Funcionais recebendo como diferencial a Farinha de Berinjela que contem efeito antioxidante, vitamina C e B3, e um elevado teor de fibras.', 'marketing_description' => 'Já a Pizza Vegetariana Integral contem farinha de berinjela. Uma excelente opção pra quem busca Vitamina C e B3 e fibras!', 'subcategory_id' => '4', 'status' => 'A'],
            ['product_id' => '18', 'sku' => 'STOD19', 'product_code' => '19', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'subcategory_id' => '2', 'status' => 'A'],
            ['product_id' => '18', 'sku' => 'STOD2445', 'product_code' => '2445', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'subcategory_id' => '2', 'status' => 'A'],
            ['product_id' => '19', 'sku' => 'STOD2682', 'product_code' => '2682', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'subcategory_id' => '2', 'status' => 'A'],
            ['product_id' => '20', 'sku' => 'STOD86', 'product_code' => '86', 'technical_description' => 'Rico em Farinhas Funcionais.', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'subcategory_id' => '2', 'status' => 'A'],
            ['product_id' => '20', 'sku' => 'STOD2437', 'product_code' => '2437', 'technical_description' => 'Rico em Farinhas Funcionais.', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'subcategory_id' => '2', 'status' => 'A'],
            ['product_id' => '21', 'sku' => 'STOD1317', 'product_code' => '1317', 'technical_description' => 'Caldo sem glúten de feijão carioca com macarrão sem glúten e bacon.', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'subcategory_id' => '3', 'status' => 'A'],
            ['product_id' => '22', 'sku' => 'STOD1643', 'product_code' => '1643', 'technical_description' => 'Sopa sem glúten a base de batata com carne, cenoura, mandioquinha e legumes.', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'subcategory_id' => '3', 'status' => 'A'],
            ['product_id' => '23', 'sku' => 'STOD3085', 'product_code' => '3085', 'technical_description' => 'Sem Glúten e Vegana.', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'subcategory_id' => '12', 'status' => 'A'],
            ['product_id' => '24', 'sku' => 'STOD2895', 'product_code' => '2895', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'subcategory_id' => '9', 'status' => 'A'],
            ['product_id' => '25', 'sku' => 'STOD2860', 'product_code' => '2860', 'technical_description' => 'Rica em Farinhas Funcionais. Contém vinagre de Maçã, que é um antioxidante e anti-inflamatório. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A, não contem amido e por isso fornecem energia sem sobrecargas ao organismo. Canela, que possui efeito termogênico que ativa o metabolismo.', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. O nosso Tortelline é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina ', 'subcategory_id' => '11', 'status' => 'A'],
            ['product_id' => '25', 'sku' => 'STOD2649', 'product_code' => '2649', 'technical_description' => 'Rica em Farinhas Funcionais. Contém vinagre de Maçã, que é um antioxidante e anti-inflamatório. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A, não contem amido e por isso fornecem energia sem sobrecargas ao organismo. Canela, que possui efeito termogênico que ativa o metabolismo.', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. O nosso Tortelline é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina ', 'subcategory_id' => '11', 'status' => 'A'],
            ['product_id' => '26', 'sku' => 'STOD2658', 'product_code' => '2658', 'technical_description' => 'Rica em Farinhas Funcionais. Contem Gengibre, alimento termogênico que ativa o metabolismo e ativa a queima de gordura corporal.', 'marketing_description' => 'O Tortelline vegano da Santo Dom contem Gengibre, que ajuda no metabolismo e queima de gordura corporal. Uma ótima e saborosa opção vegana!', 'subcategory_id' => '11', 'status' => 'A'],
            ['product_id' => '27', 'sku' => 'STOD3093', 'product_code' => '3093', 'technical_description' => 'Rico em Farinhas Funcionais. Contem uvas passas que são anti-inflamatória, antibacteriana e antioxidante e nozes, rico em ômega 3 e ômega 6.', 'marketing_description' => 'O Tortellone de Ricota da Santo Dom apresenta uvas passas, que são anti-inflamatória, antibacteirana e antioxidante. Alem disso, possui nozes, ótimo para quem busca ômega 3 e ômega 6!', 'subcategory_id' => '7', 'status' => 'A'],
            ['product_id' => '28', 'sku' => 'STOD43', 'product_code' => '43', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A.', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. A nossa zucca é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina A!', 'subcategory_id' => '7', 'status' => 'A'],
            ['product_id' => '28', 'sku' => 'STOD2429', 'product_code' => '2429', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A.', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. A nossa zucca é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina A!', 'subcategory_id' => '7', 'status' => 'A'],
            ['product_id' => '29', 'sku' => 'STOD9999', 'product_code' => '9999', 'technical_description' => '', 'marketing_description' => '', 'subcategory_id' => '14', 'status' => 'A'],
            ['product_id' => '30', 'sku' => 'STOD9998', 'product_code' => '9998', 'technical_description' => '', 'marketing_description' => '', 'subcategory_id' => '14', 'status' => 'A'],
            ['product_id' => '31', 'sku' => 'STOD9997', 'product_code' => '9997', 'technical_description' => '', 'marketing_description' => '', 'subcategory_id' => '14', 'status' => 'A'],
        ];

        foreach($lines as $line){
            $product = ProductVariant::create($line);
        }
    }
}
