<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Generator as Faker;
use App\Models\Product;
use App\Models\ProductPrice;
use App\Models\Stock;

class ProductsSeeder extends Seeder
{
    public function run(Faker $faker)
    {
        $lines = [
            ['product_id' => '2925',    'sku' => 'SD'.str_pad('2925', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha de Frango com Requeijão', 'subcategory_id' => '1', 'pack_id' => 1, 'qtde_pack' => '4', 'weight' => '240', 'unit' => 'g', 'marketing_description' => 'A nossa coxinha alem de ser saborosa e leve, não contem gluten!', 'technical_description' => 'Deliciosa, leve e com recheio. Sem Glúten.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '1927',    'sku' => 'SD'.str_pad('1927', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha de Frango com Requeijão', 'subcategory_id' => '1', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '600', 'unit' => 'g', 'marketing_description' => 'A nossa coxinha alem de ser saborosa e leve, não contem gluten!', 'technical_description' => 'Deliciosa, leve e com recheio. Sem Glúten.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '19',      'sku' => 'SD'.str_pad('19', 5,0,STR_PAD_LEFT),      'name' => 'Ravioli de Carne', 'subcategory_id' => '2', 'pack_id' => 1, 'qtde_pack' => '28', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2445',    'sku' => 'SD'.str_pad('2445', 5,0,STR_PAD_LEFT),    'name' => 'Ravioli de Carne', 'subcategory_id' => '2', 'pack_id' => 1, 'qtde_pack' => '14', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '86',      'sku' => 'SD'.str_pad('86', 5,0,STR_PAD_LEFT),      'name' => 'Rondeli de Paleta Defumada', 'subcategory_id' => '2', 'pack_id' => 1, 'qtde_pack' => '9', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'technical_description' => 'Rico em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2437',    'sku' => 'SD'.str_pad('2437', 5,0,STR_PAD_LEFT),    'name' => 'Rondeli de Paleta Defumada', 'subcategory_id' => '2', 'pack_id' => 1, 'qtde_pack' => '4', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'technical_description' => 'Rico em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2682',    'sku' => 'SD'.str_pad('2682', 5,0,STR_PAD_LEFT),    'name' => 'Ravioli de Frango', 'subcategory_id' => '2', 'pack_id' => 1, 'qtde_pack' => '14', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'As massas pré-cozidas da Santo Dom são super frescas e saborosas. E o melhor de tudo, são sem glúten!', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '1678',    'sku' => 'SD'.str_pad('1678', 5,0,STR_PAD_LEFT),    'name' => 'Canja de Galinha', 'subcategory_id' => '3', 'pack_id' => 3, 'qtde_pack' => '0', 'weight' => '300', 'unit' => 'ml', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'technical_description' => 'Caldo sem glúten de frango com arroz, batata, cenoura e legumes.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '1651',    'sku' => 'SD'.str_pad('1651', 5,0,STR_PAD_LEFT),    'name' => 'Caldo Verde', 'subcategory_id' => '3', 'pack_id' => 3, 'qtde_pack' => '0', 'weight' => '300', 'unit' => 'ml', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'technical_description' => 'Caldo sem glúten a base de batata e couve manteiga com legumes e bacon.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '1317',    'sku' => 'SD'.str_pad('1317', 5,0,STR_PAD_LEFT),    'name' => 'Sopa de Feijão', 'subcategory_id' => '3', 'pack_id' => 3, 'qtde_pack' => '0', 'weight' => '300', 'unit' => 'ml', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'technical_description' => 'Caldo sem glúten de feijão carioca com macarrão sem glúten e bacon.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '1643',    'sku' => 'SD'.str_pad('1643', 5,0,STR_PAD_LEFT),    'name' => 'Sopa de Legumes com Carne', 'subcategory_id' => '3', 'pack_id' => 3, 'qtde_pack' => '0', 'weight' => '300', 'unit' => 'ml', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'technical_description' => 'Sopa sem glúten a base de batata com carne, cenoura, mandioquinha e legumes.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2968',    'sku' => 'SD'.str_pad('2968', 5,0,STR_PAD_LEFT),    'name' => 'Pizza de Abobrinha', 'subcategory_id' => '4', 'pack_id' => 1, 'qtde_pack' => '2', 'weight' => '240', 'unit' => 'g', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'technical_description' => 'Rica em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '2631',    'sku' => 'SD'.str_pad('2631', 5,0,STR_PAD_LEFT),    'name' => 'Pizza de Abobrinha', 'subcategory_id' => '4', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '1200', 'unit' => 'g', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'technical_description' => 'Rica em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2976',    'sku' => 'SD'.str_pad('2976', 5,0,STR_PAD_LEFT),    'name' => 'Pizza Mussarela', 'subcategory_id' => '4', 'pack_id' => 1, 'qtde_pack' => '2', 'weight' => '240', 'unit' => 'g', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'technical_description' => 'Rica em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '2798',    'sku' => 'SD'.str_pad('2798', 5,0,STR_PAD_LEFT),    'name' => 'Pizza Mussarela', 'subcategory_id' => '4', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '1200', 'unit' => 'g', 'marketing_description' => 'Além de serem vegetarianas, nossas pizzas são ricas em farinhas funcionais!', 'technical_description' => 'Rica em Farinhas Funcionais.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2801',    'sku' => 'SD'.str_pad('2801', 5,0,STR_PAD_LEFT),    'name' => 'Pizza Vegetariana Integral', 'subcategory_id' => '4', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '1200', 'unit' => 'g', 'marketing_description' => 'Já a Pizza Vegetariana Integral contem farinha de berinjela. Uma excelente opção pra quem busca Vitamina C e B3 e fibras!', 'technical_description' => 'Rica em Farinhas Funcionais recebendo como diferencial a Farinha de Berinjela que contem efeito antioxidante, vitamina C e B3, e um elevado teor de fibras.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '167',     'sku' => 'SD'.str_pad('167', 5,0,STR_PAD_LEFT),     'name' => 'Massa para Pastel', 'subcategory_id' => '5', 'pack_id' => 4, 'qtde_pack' => '12', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'A nossa Massa para pastel é leve  e não contem lactose!', 'technical_description' => 'Rico em Farinhas Funcionais, não contem lactose.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '159',     'sku' => 'SD'.str_pad('159', 5,0,STR_PAD_LEFT),     'name' => 'Massa para Pizza', 'subcategory_id' => '5', 'pack_id' => 4, 'qtde_pack' => '5', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'A nossa Massa para pizza possui semente de Girassol, que ajuda na saúde do sistema imunológico e na produção de anticorpos, alem de ser levissíma!', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Contem como diferencial a Semente de Girassol,  com importante papel para a promoção da saúde do sistema imunológico e produção de anticorpos e o AMARANTO, fonte de proteínas, rico em minerais, como o cálcio, o magnésio e o fósforo, o amaranto fortalece os ossos e os dentes, além de ser rico em Ferro.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '140',     'sku' => 'SD'.str_pad('140', 5,0,STR_PAD_LEFT),     'name' => 'Massa de Lasanha', 'subcategory_id' => '6', 'pack_id' => 1, 'qtde_pack' => '12', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'A nossa para Lasanha é rica em farinhas funcionais e não contem glúten!', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '43',      'sku' => 'SD'.str_pad('43', 5,0,STR_PAD_LEFT),      'name' => 'Zucca', 'subcategory_id' => '7', 'pack_id' => 1, 'qtde_pack' => '25', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. A nossa zucca é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina A!', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2429',    'sku' => 'SD'.str_pad('2429', 5,0,STR_PAD_LEFT),    'name' => 'Zucca', 'subcategory_id' => '7', 'pack_id' => 1, 'qtde_pack' => '13', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. A nossa zucca é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina A!', 'technical_description' => 'Rica em Farinhas Funcionais, não contem lactose. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '124',     'sku' => 'SD'.str_pad('124', 5,0,STR_PAD_LEFT),     'name' => 'Buffalina', 'subcategory_id' => '7', 'pack_id' => 1, 'qtde_pack' => '25', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'A Buffalina, por ser feita com mussarela de Búfala, contem menos gordura e sódio. É uma ótima fonte de proteína, cálcio e vitaminas A,B2 e D.', 'technical_description' => 'Rica em Farinhas Funcionais. Comparado a mussarela de leite de vaca a mussarela de Búfala contem menos gordura e sódio, além de ser ótima fonte de proteína, Cálcio, Vitaminas A, B2 e D.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2410',    'sku' => 'SD'.str_pad('2410', 5,0,STR_PAD_LEFT),    'name' => 'Buffalina', 'subcategory_id' => '7', 'pack_id' => 1, 'qtde_pack' => '13', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'A Buffalina, por ser feita com mussarela de Búfala, contem menos gordura e sódio. É uma ótima fonte de proteína, cálcio e vitaminas A,B2 e D.', 'technical_description' => 'Rica em Farinhas Funcionais. Comparado a mussarela de leite de vaca a mussarela de Búfala contem menos gordura e sódio, além de ser ótima fonte de proteína, Cálcio, Vitaminas A, B2 e D.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '3093',    'sku' => 'SD'.str_pad('3093', 5,0,STR_PAD_LEFT),    'name' => 'Tortellone de Ricota', 'subcategory_id' => '7', 'pack_id' => 1, 'qtde_pack' => '15', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'O Tortellone de Ricota da Santo Dom apresenta uvas passas, que são anti-inflamatória, antibacteirana e antioxidante. Alem disso, possui nozes, ótimo para quem busca ômega 3 e ômega 6!', 'technical_description' => 'Rico em Farinhas Funcionais. Contem uvas passas que são anti-inflamatória, antibacteriana e antioxidante e nozes, rico em ômega 3 e ômega 6.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2933',    'sku' => 'SD'.str_pad('2933', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha Vegana de Alho Poró', 'subcategory_id' => '8', 'pack_id' => 1, 'qtde_pack' => '4', 'weight' => '240', 'unit' => 'g', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'technical_description' => 'O Alho Poró é uma fibra prebiótica que auxilia na defesa da mucosa intestinal.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2623',    'sku' => 'SD'.str_pad('2623', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha Vegana de Alho Poró', 'subcategory_id' => '8', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '600', 'unit' => 'g', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'technical_description' => 'O Alho Poró é uma fibra prebiótica que auxilia na defesa da mucosa intestinal.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2771',    'sku' => 'SD'.str_pad('2771', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha Vegana de Carne de Jaca', 'subcategory_id' => '8', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '600', 'unit' => 'g', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'technical_description' => 'A Carne de Jaca é rica em vitaminas e minerais, como o ferro, o potássio, o cálcio e o fósforo. Tem o poder de prevenir a anemia, regular a pressão arterial e combater radicais livres.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2763',    'sku' => 'SD'.str_pad('2763', 5,0,STR_PAD_LEFT),    'name' => 'Coxinha Vegana de Palmito', 'subcategory_id' => '8', 'pack_id' => 2, 'qtde_pack' => '10', 'weight' => '600', 'unit' => 'g', 'marketing_description' => 'Já teve o desejo de comer uma coxinha mas deixou passar por causa do frango? Você pode experimentar nossa coxinha vegana! São leves e deliciosas', 'technical_description' => 'O Palmito tem baixo teor de gorduras, fornece nutrientes como vitaminas A, C, do complexo B e importantes minerais como o sódio e o potássio.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '2379',    'sku' => 'SD'.str_pad('2379', 5,0,STR_PAD_LEFT),    'name' => 'Massa Vegana para Pastel', 'subcategory_id' => '9', 'pack_id' => 4, 'qtde_pack' => '10', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2895',    'sku' => 'SD'.str_pad('2895', 5,0,STR_PAD_LEFT),    'name' => 'Talharine Vegano', 'subcategory_id' => '9', 'pack_id' => 1, 'qtde_pack' => '0', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2747',    'sku' => 'SD'.str_pad('2747', 5,0,STR_PAD_LEFT),    'name' => 'Massa Vegana para Lasanha', 'subcategory_id' => '10', 'pack_id' => 1, 'qtde_pack' => '12', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas da Santo Dom são ricas em farinhas funcionais. As nossas massas veganas contem vingagre de maçã, que é um antioxidante e anti-inflamatório', 'technical_description' => 'Rica em Farinhas Funcionais. Contem vinagre de Maçã, que é um antioxidante e anti-inflamatório.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2739',    'sku' => 'SD'.str_pad('2739', 5,0,STR_PAD_LEFT),    'name' => 'Nhoque Vegano de Batata Doce', 'subcategory_id' => '10', 'pack_id' => 1, 'qtde_pack' => '100', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'A batata doce já é muito conhecida por aqueles que buscam uma opção de carboidrato ', 'technical_description' => 'A batata doce é um carboidrato de absorção lenta, portanto, não aumenta de forma brusca os níveis de glicose no sangue, fonte de vitaminas A e C.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2712',    'sku' => 'SD'.str_pad('2712', 5,0,STR_PAD_LEFT),    'name' => 'Nhoque Vegano de Batata Doce', 'subcategory_id' => '10', 'pack_id' => 1, 'qtde_pack' => '50', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'A batata doce já é muito conhecida por aqueles que buscam uma opção de carboidrato ', 'technical_description' => 'A batata doce é um carboidrato de absorção lenta, portanto, não aumenta de forma brusca os níveis de glicose no sangue, fonte de vitaminas A e C.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2860',    'sku' => 'SD'.str_pad('2860', 5,0,STR_PAD_LEFT),    'name' => 'Tortelline Vegano de Abóbora', 'subcategory_id' => '11', 'pack_id' => 1, 'qtde_pack' => '30', 'weight' => '400', 'unit' => 'g', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. O nosso Tortelline é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina ', 'technical_description' => 'Rica em Farinhas Funcionais. Contém vinagre de Maçã, que é um antioxidante e anti-inflamatório. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A, não contem amido e por isso fornecem energia sem sobrecargas ao organismo. Canela, que possui efeito termogênico que ativa o metabolismo.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '2649',    'sku' => 'SD'.str_pad('2649', 5,0,STR_PAD_LEFT),    'name' => 'Tortelline Vegano de Abóbora', 'subcategory_id' => '11', 'pack_id' => 1, 'qtde_pack' => '15', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'As massas frescas da Santo Dom são ricas em farinhas funcionaise não contem Lactose. O nosso Tortelline é feita com recheio de Abóbora Cabotiá, ótima para quem busca Vitamina ', 'technical_description' => 'Rica em Farinhas Funcionais. Contém vinagre de Maçã, que é um antioxidante e anti-inflamatório. Ingrediente principal do recheio é a Abóbora Cabotiá, rico em vitamina A, não contem amido e por isso fornecem energia sem sobrecargas ao organismo. Canela, que possui efeito termogênico que ativa o metabolismo.', 'minimal_stock' => '10', 'featured' => '1'],
            ['product_id' => '2658',    'sku' => 'SD'.str_pad('2658', 5,0,STR_PAD_LEFT),    'name' => 'Tortelline Vegano de Legumes', 'subcategory_id' => '11', 'pack_id' => 1, 'qtde_pack' => '15', 'weight' => '200', 'unit' => 'g', 'marketing_description' => 'O Tortelline vegano da Santo Dom contem Gengibre, que ajuda no metabolismo e queima de gordura corporal. Uma ótima e saborosa opção vegana!', 'technical_description' => 'Rica em Farinhas Funcionais. Contem Gengibre, alimento termogênico que ativa o metabolismo e ativa a queima de gordura corporal.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '3085',    'sku' => 'SD'.str_pad('3085', 5,0,STR_PAD_LEFT),    'name' => 'Sopa de Mandioquinha', 'subcategory_id' => '12', 'pack_id' => 3, 'qtde_pack' => '0', 'weight' => '300', 'unit' => 'ml', 'marketing_description' => 'Os caldos e sopas da Santo Dom são ótimas para aqueles dias mais frios e o mlehor, não contem glúten!', 'technical_description' => 'Sem Glúten e Vegana.', 'minimal_stock' => '10', 'featured' => '0'],
            ['product_id' => '3009',    'sku' => 'SD'.str_pad('3009', 5,0,STR_PAD_LEFT),    'name' => 'Molho de Tomate', 'subcategory_id' => '13', 'pack_id' => 5, 'qtde_pack' => '0', 'weight' => '500', 'unit' => 'g', 'marketing_description' => '', 'technical_description' => 'Molho ao sugo Vegano e sem glúten.', 'minimal_stock' => '10', 'featured' => '0'],
        ];

        foreach($lines as $line){
            $product = Product::create($line);

            Stock::create([
                'product_id'    => $product->product_id,
                'quantity'      => $faker->numberBetween(20, 100)
            ]);

            for ($i=0; $i < mt_rand(1, 4); $i++) {
                $max = ($i == 0) ? '' : '+60 days';
                ProductPrice::create([
                    'product_id'    => $product->product_id,
                    'table_id'      => '1',
                    'start_date'    => $faker->unique()->dateTimeThisYear($max),
                    'price'         => $faker->randomFloat(2, 9, 45),
                ]);

            }
        }
    }
}
